#include "driver/gpio.h"

#define STATUS_LED_DI GPIO_NUM_19
#define STATUS_LED_CI GPIO_NUM_15
#define LED_PIN_1 GPIO_NUM_12
#define LED_PIN_0 GPIO_NUM_13
#define LED_PIN_2 GPIO_NUM_14
#define LED_PIN_3 GPIO_NUM_21
#define LED_PIN_4 GPIO_NUM_22
#define LED_PIN_5 GPIO_NUM_27
#define LED_PIN_7 GPIO_NUM_32
#define LED_PIN_6 GPIO_NUM_33
#define AUX_INPUT_DETECT GPIO_NUM_39